- name: Print
  ansible.builtin.debug:
    msg: Hellow from Role

- name: Print URL
  ansible.builtin.debug:
    msg: URL == {{URL}}

- name: Copy a file
  copy: 
    src: sample.txt
    dest: /tmp/sample.txt
  vars:
    COURSE: DEVOPS

- name: Copy a template
  template:
    src: sample.txt
    dest: /tmp/sample-temp.txt
  vars:
    COURSE: DEVOPS


