- name: Print
  ansible.builtin.debug:
    msg: Hellow from Role

- name: Print URL
  ansible.builtin.debug:
    msg: URL == {{URL}}

- name: Copy a file
  copy:
    src: sample.txt
    dest: /tmp/sample.txt